name: Build and Publish

on:
  workflow_dispatch:
    inputs:
      app-version:
        description: "version"
        default: "v1.0.0"

jobs:
  dev-connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the Git tag name
        id: tag_name
        run: echo "::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d '/' -f 3)"

      - name: DEV Connect
        run: |
          docker login ghcr.io -u MUUBAA -p ${{ secrets.GIT_PAT }}
          docker build --no-cache -t ghcr.io/dev-connect/app:${{ github.event.inputs.app-version }} -f ./Dockerfile .
          docker push ghcr.io/dev-connect/app:${{ github.event.inputs.app-version }}
